### ISSUE TITLE
Open up github disscussion

### ISSUE THREAD

**Issue by JustSimplyKyle** [Kirottu/anyrun#27]
Would help giving people advice, ~and a place to show off configs~

![image](https://user-images.githubusercontent.com/68589851/236678036-b8d4b4e1-fd18-4193-ab85-c228bd9cc81f.png)
```css
#entry {
  background-color: alpha(@theme_fg_color,0.1);
  border: 1px solid rgba(255,255,255,0.15);
  border-radius: 16px;
}

#main {
  background-color: alpha(@theme_bg_color,0.3);
  border: 1px solid rgba(255,255,255,0.15);
  border-radius: 16px;
}

#plugin {
  background-color: transparent;
}

#window {
  background: none;
}
```

btw, when I try to use `currentColor` I didn't get the color set by gtk, instead I got white. Are there any alternatives to directly using `@theme_bg/fg_color`?
